# Generated by Django 2.2.14 on 2020-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memberships', models.CharField(choices=[('P', 'premium'), ('S', 'saver'), ('N', 'none')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
