# Generated by Django 2.2.14 on 2020-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201011_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='points_used',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_wallet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
