# Generated by Django 2.2.14 on 2020-10-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201011_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='points_used',
        ),
    ]
