# Generated by Django 2.2.14 on 2020-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201011_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
    ]
