# Generated by Django 2.2.14 on 2020-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_userprofile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.IntegerField(default=10000, null=True),
        ),
    ]
