# Generated by Django 2.2.14 on 2020-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201015_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.CharField(blank=True, choices=[('N', 'Nouveauté'), ('QL', 'Quantité limitée'), ('ND', 'Non disponible')], max_length=2, null=True),
        ),
    ]
