# Generated by Django 2.2.14 on 2020-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201015_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_wallet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
