# Generated by Django 2.2.14 on 2020-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201015_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='memberships',
            field=models.CharField(choices=[('P', 'Premium'), ('S', 'Saver'), ('F', 'Free')], default='N', max_length=1),
        ),
    ]
